### ISSUE TITLE
Error running CodeceptJS E2E Test - "TypeError: Cannot read properties of undefined (reading 'endsWith')"

### ISSUE THREAD

**Issue by bipinct** [HumanSignal/label-studio-frontend#1633]
**Description:**

### Problem:

While attempting to run E2E tests with CodeceptJS in the Label Studio Frontend, I encountered the following error:

```plaintext
TypeError: Cannot read properties of undefined (reading 'endsWith')
at /home/bct/CODEBASE/label-studio-frontend/e2e/plugins/errorsCollector.js:175:16
```

This error occurs specifically during a test that checks the functionality of audio controls. The relevant output is as follows:

```plaintext
Audio Controls --
Warning: Timeout was set to 2400secs.
Global timeout should be specified in seconds.
  ✖ Check the audio controls work in 9991ms

-- FAILURES:

  1) Audio Controls
       Check the audio controls work:
     TypeError: Cannot read properties of undefined (reading 'endsWith')
      at /home/bct/CODEBASE/label-studio-frontend/e2e/plugins/errorsCollector.js:175:16
  
  Scenario Steps:
  - I.amOnPage("/") at Test.<anonymous> (./tests/audio/audio-controls.test.js:65:5)
  - I.executeScript(setFeatureFlags) at Object.setFeatureFlags (./fragments/LabelStudio.js:29:7)
  
  Artifacts:
  - screenshot: /home/bct/CODEBASE/label-studio-frontend/e2e/output/Check_the_audio_controls_work.failed.png
```

I have reviewed the relevant test file (`./tests/audio/audio-controls.test.js`) and the `errorsCollector.js` file, but I am struggling to identify the root cause of this `TypeError`. Any insights into what might be causing this error and suggestions on how to resolve it would be greatly appreciated.

### Additional Information:

- The CodeceptJS version is `3.5.6`.

Thank you for your assistance!

**Comment by bipinct** [comment]
we did some customization in default label studio which broke the test cases
